### ISSUE TITLE
api_key is converted to all lowercase

### ISSUE THREAD

**Issue by chris-79** [pixelfear/Statamic-Webhooks#4]
I've set an API Key to a randomly generated, mixed-case, alphanumeric string, but the key, as set in `_config/add-ons/webhooks/webhooks.yaml`, gets converted to all lowercase by `$this->fetchConfig('api_key', Helper::getRandomString())`. This causes the check to fail.

**Comment by jasonvarga** [comment]
Good catch. Should be fixed now in 9160742bd752bde42401b4d1eb491b0c96059ec1.

**Comment by chris-79** [comment]
Nice :+1:
